language: java

jdk:
  - oraclejdk8
  - oraclejdk7

script:
  mvn clean package

after_script:
  - cat */target/surefire-reports/*.txt

after_success:
  - mvn clean cobertura:cobertura coveralls:report
  
notifications:
  slack: hakafederation:MtSKauyCZcYkfkaLhFlL9Ecx
